### PR TITLE
Added XML, JSON and Yaml support

### PR DESCRIPTION
**Pull request by OhMyMndy**
Compiled features with this pull request:

`$ universal-ctags --version                                                                                                                                                      
Universal Ctags 0.0.0(f42b573f), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec 11 2019, 14:40:50
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +packcc
`

### CODE REVIEW

**Comment by tartley** [comment]
Hey @Mandy91, thanks heaps for the PR. This is indeed a worthy goal.

In case you didn't see it, I have plans to add all compile-time flags that are present in the apt package:  #21  But I'd be delighted to merge this PR even if it only adds some of those flags.

Travis reports a build failure: I'm guessing that the resulting snap of ctags needs some shared libraries installed. They must be already installed on your machine, so you see no problems. But they aren't installed on the travis build box, and might not be installed on a user's box. So we need to tell snapcraft to installs whatever shared libraries are used to parse the new file types. I'm not yet sure how to do that. If you can figure it out, great, or I'll happily have a try myself sometime soon (albeit not today). I'll post any progress I make here, so we can pool resources.

Thank you!

**Comment by Mandy91** [comment]
Hello @tartley, I added libjansson4 to the snapcraft.yml file and now it is building successfully :+1:

**Comment by tartley** [comment]
@Mandy91 You are amazing. Thank you!

**Comment by tartley** [comment]
I made a new release to the snapstore, on 'edge', tested it, and then promoted it to 'stable'. Thank you for this fabulous improvement.

If you have anything else you'd like to see fixed, file an issue to let me know, I'll happily help if I can.

**Comment by Mandy91** [comment]
Glad I could help :-), I'll have a go at including all build dependencies and runtime dependencies later this week. Also, do you think it is a good idea to change the confinement mode to "classic"? I had problems earlier where a Vim plugin (which used ctags) could not read the hosts /tmp directory, which is not possible in Snaps with strict confinement...

**Comment by tartley** [comment]
@Mandy91 Brilliant. If you do get time to look at the extra dependencies, I *think* what we're aiming for is to match the compile-time flags supported in the 'apt' version. Let me know if you think that's wrong.

Also: You are absolutely right about being a classic snap. I dragged my heels about it somewhat, exploring what is possible as a regular snap with interfaces, because I wanted to learn what was and was not possible. But just yesterday I requested the snapstore to make us classic. See https://github.com/universal-ctags/ctags-snap/issues/4#issuecomment-566230666

**Pull request merged**
